"""add contact_phone and contact_email to apartments

Revision ID: c3cda027bbfe
Revises: f1a2b3c4d5e6
Create Date: 2026-03-29 10:57:06.041075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cda027bbfe'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('apartments', sa.Column('contact_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'contact_email')
    op.drop_column('apartments', 'contact_phone')
    # ### end Alembic commands ###
