"""add true cost columns

Revision ID: e98533caec98
Revises: b67261628783
Create Date: 2026-03-27 20:31:01.145707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e98533caec98'
down_revision: Union[str, None] = 'b67261628783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('pet_rent', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('parking_fee', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('amenity_fee', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('application_fee', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('security_deposit', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_electric', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_gas', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_water', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_internet', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_renters_insurance', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('est_laundry', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('utilities_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('apartments', sa.Column('true_cost_monthly', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('true_cost_move_in', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'true_cost_move_in')
    op.drop_column('apartments', 'true_cost_monthly')
    op.drop_column('apartments', 'utilities_included')
    op.drop_column('apartments', 'est_laundry')
    op.drop_column('apartments', 'est_renters_insurance')
    op.drop_column('apartments', 'est_internet')
    op.drop_column('apartments', 'est_water')
    op.drop_column('apartments', 'est_gas')
    op.drop_column('apartments', 'est_electric')
    op.drop_column('apartments', 'security_deposit')
    op.drop_column('apartments', 'application_fee')
    op.drop_column('apartments', 'amenity_fee')
    op.drop_column('apartments', 'parking_fee')
    op.drop_column('apartments', 'pet_rent')
    # ### end Alembic commands ###
